version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: product-catalog-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
